### ISSUE TITLE
Gnome Calendar is shipped as a regular package

### ISSUE THREAD

**Issue by user1-github** [arkanelinux/flatpak-init-arkane#1]
I noticed that Gnome Calendar is shipped as a regular package instead of the one from Flathub. So out of curiosity, is there a particular issue with the Flathub version of Gnome Calendar which is why a package version is shipped instead?

**Comment by dennis1248** [comment]
If I recall properly the issue was that any calendar entries created in gnome-calendar did not appear in the GNOME UI. But this no longer seems to be an issue, I will swap the packages out.

**Comment by dennis1248** [comment]
Fixed with https://github.com/arkanelinux/arkane-flatpak-init/commit/fd61213a2f6b5ef04e2b106ec379cb9a55f196c6 and https://github.com/arkanelinux/arkdep/commit/8d8327a6867eb87e1dd58e0fc84438bb96daf4b6
